[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
adapters = { path = "../adapters" }
db = { path = "../db" }

actix-web = "4.4.0"