[package]
name = "ambient-message-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
tokio-tungstenite = "0.20.1"
futures-util = "0.3"