[package]
name = "ambient-message-server"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.4.0"
actix-http = "3.4.0"
actix-rt = "2.7"

infrastructure = { path = "crates/infrastructure" }