[package]
name = "ambient_message_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ambient_message_server_bin"
path = "src/main.rs"

[lib]
name = "ambient_message_server_lib"
path = "src/lib.rs"


[dependencies]
tokio = { version = "1.28.1", features = ["full"] }
tokio-tungstenite = "0.20.1"
futures-util = "0.3"
rand = "0.8.5"
diesel = { version = "2.1.4", features = ["postgres", "r2d2", "uuid"] }
dotenvy = "0.15"
mockall = "0.11.4"
readonly = "0.2.11"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1.74"
uuid = { version = "1.6.1", features = ["v4"] }
r2d2 = "0.8.10"
inject = "0.1.3"

