[package]
name = "application"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
domain = { path = "../domain" }

async-trait = "0.1.74"
uuid = { version = "1.6.1", features = ["v4"] }