[package]
name = "application"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
domain = { path = "../domain" }

uuid = { version = "1.6.1", features = ["v4"] }
actix-web-httpauth = "0.8.1"
actix-web = "4.4.1"
jsonwebtoken = "9.2.0"
anyhow = "1.0.79"
thiserror = "1.0.56"